# Generated by Django 4.2.5 on 2024-01-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Категория',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='serv.category', verbose_name='Категория'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='project_image',
        ),
    ]
