# Generated by Django 4.2.5 on 2024-10-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0002_remove_post_категория_post_category_alter_post_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to='project/media/'),
        ),
    ]
